### ISSUE TITLE
tool to create mbf font out of bdf

### ISSUE THREAD

**Issue by epicfilemcnulty** [lecram/congif#1]
First of all, thanks for the excellent, fast and lightweight tool.

Do you have a tool to convert bdf fonts into mbf? Somehow you've created misc-fixed-6x10.mbf file, so my guess it was converted from bdf?

**Comment by lecram** [comment]
Thanks for the kind words.

I've used a Lua script to convert from bdf to mbf. The script was incomplete and buggy. It only worked with certain fonts.

I'm putting together a new program to do the conversion and will update this issue with a link when it's done.

**Comment by lecram** [comment]
Hi, please check this repo:
https://github.com/lecram/mbf-util
The bdf2mbf tool there should be usable. Feel free to report any bugs.
